#!/bin/bash
# a script that downloads a sublime installer and runs it and downloads zsh for linux terminal


if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "uid is ${UID}"
echo "user is ${USER}"
echo "username is ${USERNAME}"



#(http://stackoverflow.com/questions/7358611/bash-get-users-home-directory-when-they-run-a-script-as-root)
USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)


#Gets username even if running as sudo http://stackoverflow.com/questions/3522341/identify-user-in-a-bash-script-called-by-sudo
echo -e "\e[7m*** Creating temp location on /home/$SUDO_USER/cache/...\e[0m"

mkdir -p /home/$SUDO_USER/cache
cd /home/$SUDO_USER/cache

echo "Do you wish to have git installed"
select yn in "Yes" "No"; do
	case $yn in
		Yes ) apt-get install git-core && apt-get update; break;;
		No )  break;;
	esac
done


echo "Do you wish to install sublime-text-3?"
select yn in "Yes" "No"; do
	case $yn in
		Yes ) #wget master.zip https://github.com/kazyka/sublime-text-linux-installer/archive/master.zip; 
			  echo -e "\e[7m*** File downloaded\e[0m"
			  unzip master.zip
			  cd sublime-text-linux-installer-master
			  #chmod +x ./st3install && sudo ./st3install
			  cd ..
			  #rm -rf master.zip
			  #rm -rf sublime-text-linux-installer-master
			  break;;
		No ) break;;
	esac
done

echo "Do you wish to install zsh?"
select yn in "Yes" "No"; do
	case $yn in
		Yes ) #wget master.zip https://github.com/kazyka/sublime-text-linux-installer/archive/master.zip; 
			  echo -e "\e[7m*** File downloaded\e[0m"
			  
			  #cd 
			  
			  #cd ..
			  #rm -rf master.zip
			  #rm -rf sublime-text-linux-installer-master
			  break;;
		No ) break;;
	esac
done


echo "Do you wish to install texlive and texmaker"
select yn in "Yes" "No"; do
	case $yn in
		Yes )
			#apt-get update && apt-get install texlive-full
			#Detects system
			if [ "i686" = `uname -m` ]; then
			#http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3000_x32.tar.bz2
			echo -e "\e[7m*** System x86 detected.\e[0m"
				if [ "14.04" = `lsb_release -rs` ]; then
				#
				echo -e "\e[7m*** System 14.04 detected.\e[0m"
				#wget http://www.xm1math.net/texmaker/texmaker_ubuntu_14.04_4.5_i386.deb
				elif [ "15.04" = `lsb_release -rs` ]; then
				#
				echo -e "\e[7m*** System 15.04 detected.\e[0m"
				#wget http://www.xm1math.net/texmaker/texmaker_ubuntu_15.04_4.5_i386.deb
				elif [ "15.10" = `lsb_release -rs` ]; then
				#
				echo -e "\e[7m*** System 15.10 detected.\e[0m"
				#wget http://www.xm1math.net/texmaker/texmaker_ubuntu_15.10_4.5_i386.deb
				fi
			elif [ "x86_64" = `uname -m` ]; then
			#http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3000_x64.tar.bz2
			echo -e "\e[7m*** System x86-64 detected.\e[0m"
				if [ "14.04" = `lsb_release -rs` ]; then
				#
				echo -e "\e[7m*** System 14.04 detected.\e[0m"
				#wget http://www.xm1math.net/texmaker/texmaker_ubuntu_14.04_4.5_amd64.deb -O texmaker.deb
				elif [ "15.04" = `lsb_release -rs` ]; then
				#
				echo -e "\e[7m*** System 15.04 detected.\e[0m"
				#wget http://www.xm1math.net/texmaker/texmaker_ubuntu_15.04_4.5_amd64.deb -O texmaker.deb
				elif [ "15.10" = `lsb_release -rs` ]; then
				#
				echo -e "\e[7m*** System 15.10 detected.\e[0m"
				#wget http://www.xm1math.net/texmaker/texmaker_ubuntu_15.10_4.5_amd64.deb -O texmaker.deb
				fi
			fi
			 break;;
		No ) break;;
	esac
done

echo -e "\e[7m*** Deleting temp location on /home/$SUDO_USER/cache/...\e[0m"

cd /home/$SUDO_USER/
rm -rf cache
